version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - PORT=8000
      - SECRET_KEY=your_secret_key_here
    volumes:
      - ./static/uploads:/app/static/uploads
